# PodDisruptionBudget for  Statefulsets
{{- if .Values.solace.podDisruptionBudgetForHA }}
{{- if .Values.solace.redundancy }}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "solace.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "solace.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "solace.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}